export const LENGTH = 'LENGTH';
export const INCLUDE_UPPERCASE = 'INCLUDE_UPPERCASE';
export const INCLUDE_LOWERCASE = 'INCLUDE_LOWERCASE';
export const INCLUDE_NUMBERS = 'INCLUDE_NUMBERS';
export const INCLUDE_SYMBOLS = 'INCLUDE_SYMBOLS';
export const GENERATE_PASSWORD = 'GENERATE_PASSWORD';
